apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.projectName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.projectName }}
  template:
    metadata:
      labels:
        app: {{ .Values.projectName }}
    spec:
      containers:
      - name: {{ .Values.projectName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
